url: 
baseurl: 

# Site settings
title: UW Mode Lab
email: 
description: "Emily B. Fox and Carlos Guestrin's research group at the University of Washington."


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/uw-mode/
  - title: github-alt
    url: http://github.com/dynamode/

# Postal address (add as many lines as necessary)
#address:
#  - line: 
#  - line: 

# Build settings
markdown: kramdown
permalink: rouge

gems:
  - jekyll-sitemap
  - jekyll/scholar

# Jekyll Scholar Bibtex Formatting
scholar:
  style: apa
  locale: en

  sort_by: year, booktitle, author
  order: descending, descending, ascending 

  source: ./_data
  bibliography: publications.bib
  bibliography_template: bib

  replace_strings: true
  join_strings:    true

#  details_dir:    bibliography
#  details_layout: bib_details.html
#  details_link:   " Details"

  query: "@*"

  repository: ./pdf


# Include/Exclude
include:
exclude: ["Rakefile", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "build.sh","deploy-to-master.sh"]
